#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCustomHelpers.Razor
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCustomHelpers;
    
    #line 5 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
    using MvcCustomHelpers.Classes;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class ControlBusquedaHelpers : System.Web.WebPages.HelperPage
    {

#line 7 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
public static System.Web.WebPages.HelperResult ControlBusqueda(string id, List<ControlBusquedaColumna> campos, string action, string nameProp, string hiddenText, string descriptionText)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 8 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
 
    

#line default
#line hidden

#line 17 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <a");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-danger btn-md\"");

WriteAttributeTo(__razor_helper_writer, "onclick", Tuple.Create(" onclick=\"", 952), Tuple.Create("\"", 1101)
, Tuple.Create(Tuple.Create("", 962), Tuple.Create("mostrarModalBusqueda(\'modal-", 962), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 990), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 990), false)
, Tuple.Create(Tuple.Create("", 993), Tuple.Create("\',", 993), true)
, Tuple.Create(Tuple.Create(" ", 995), Tuple.Create("\'search-table-", 996), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
              , Tuple.Create(Tuple.Create("", 1010), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1010), false)
, Tuple.Create(Tuple.Create("", 1013), Tuple.Create("\',", 1013), true)
, Tuple.Create(Tuple.Create(" ", 1015), Tuple.Create("\'", 1016), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                     , Tuple.Create(Tuple.Create("", 1017), Tuple.Create<System.Object, System.Int32>(action

#line default
#line hidden
, 1017), false)
, Tuple.Create(Tuple.Create("", 1024), Tuple.Create("\',", 1024), true)
, Tuple.Create(Tuple.Create(" ", 1026), Tuple.Create("\'", 1027), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                , Tuple.Create(Tuple.Create("", 1028), Tuple.Create<System.Object, System.Int32>(nameProp

#line default
#line hidden
, 1028), false)
, Tuple.Create(Tuple.Create("", 1037), Tuple.Create("\',", 1037), true)
, Tuple.Create(Tuple.Create(" ", 1039), Tuple.Create("\'input-search-", 1040), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                          , Tuple.Create(Tuple.Create("", 1054), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1054), false)
, Tuple.Create(Tuple.Create("", 1057), Tuple.Create("\',", 1057), true)
, Tuple.Create(Tuple.Create(" ", 1059), Tuple.Create("\'", 1060), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                                 , Tuple.Create(Tuple.Create("", 1061), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1061), false)
, Tuple.Create(Tuple.Create("", 1064), Tuple.Create("\',", 1064), true)
, Tuple.Create(Tuple.Create(" ", 1066), Tuple.Create("\'", 1067), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                                        , Tuple.Create(Tuple.Create("", 1068), Tuple.Create<System.Object, System.Int32>(hiddenText

#line default
#line hidden
, 1068), false)
, Tuple.Create(Tuple.Create("", 1079), Tuple.Create("\',", 1079), true)
, Tuple.Create(Tuple.Create(" ", 1081), Tuple.Create("\'", 1082), true)

#line 18 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                                                       , Tuple.Create(Tuple.Create("", 1083), Tuple.Create<System.Object, System.Int32>(descriptionText

#line default
#line hidden
, 1083), false)
, Tuple.Create(Tuple.Create("", 1099), Tuple.Create("\')", 1099), true)
);

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-search\"");

WriteLiteralTo(__razor_helper_writer, "></i></a>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1145), Tuple.Create("\"", 1159)
, Tuple.Create(Tuple.Create("", 1150), Tuple.Create("modal-", 1150), true)

#line 19 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 1156), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1156), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"modal fade\"");

WriteLiteralTo(__razor_helper_writer, " role=\"dialog\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-dialog\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\r\n            <!-- Modal content-->\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-content\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"close\"");

WriteLiteralTo(__razor_helper_writer, " data-dismiss=\"modal\"");

WriteLiteralTo(__razor_helper_writer, ">&times;</button>\r\n                    <h4");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-title\"");

WriteLiteralTo(__razor_helper_writer, ">Búsqueda</h4>\r\n                </div>\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <input");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control textBuscar\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1632), Tuple.Create("\"", 1653)
, Tuple.Create(Tuple.Create("", 1637), Tuple.Create("input-search-", 1637), true)

#line 29 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 1650), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1650), false)
);

WriteLiteralTo(__razor_helper_writer, " placeholder=\"Escriba para buscar ...\"");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " style=\"margin-top:50px\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <table");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1788), Tuple.Create("\"", 1809)
, Tuple.Create(Tuple.Create("", 1793), Tuple.Create("search-table-", 1793), true)

#line 31 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 1806), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1806), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"tablaBusqueda table table-bordered table-striped\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                            <thead>\r\n                            <th>EntityID<" +
"/th>\r\n");


#line 34 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                            

#line default
#line hidden

#line 34 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                             foreach (ControlBusquedaColumna campo in campos)
                            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                                <th>");


#line 36 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
      WriteTo(__razor_helper_writer, campo.Propiedad);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</th>\r\n");


#line 37 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                            <th></th>\r\n                            </thead>\r\n    " +
"                        ");

WriteLiteralTo(__razor_helper_writer, "\r\n                        </table>\r\n                    </div>\r\n                <" +
"/div>\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-footer\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default\"");

WriteLiteralTo(__razor_helper_writer, " data-dismiss=\"modal\"");

WriteLiteralTo(__razor_helper_writer, ">Cerrar</button>\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n " +
"   </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        //agrego las columnas para el buscador actual\r\n        var " +
"columnasActuales = [];\r\n        columnasActuales.push({ \'data\': \'EntityID\', \'vis" +
"ible\': false });\r\n");


#line 55 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
        

#line default
#line hidden

#line 55 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
         foreach (ControlBusquedaColumna campo in campos)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "columnasActuales.push({ \'data\': \'");


#line 57 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                         WriteTo(__razor_helper_writer, campo.Propiedad);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', \'title\': \'");


#line 57 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                      WriteTo(__razor_helper_writer, campo.Titulo);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\' });");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 58 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        //guardo las columnas y su id en el array que se define al principio de l" +
"a pagina\r\n        var obj = [];\r\n        obj.push(\'");


#line 61 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n        obj.push(columnasActuales);\r\n        columns.push(obj);\r\n        //g" +
"uardo el reload del buscador actual con su id\r\n        var reload = [];\r\n       " +
" reload.push(\'");


#line 66 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n        reload.push(false);\r\n        reloades.push(reload);\r\n    </script>\r\n" +
"");


#line 70 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"


#line default
#line hidden
});

#line 70 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
}
#line default
#line hidden

#line 74 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
public static System.Web.WebPages.HelperResult ControlBusqueda(string id, List<ControlBusquedaColumna> campos, string action, string nameProp, string hiddenText, string descriptionText, List<ControlBusquedaParametros> parametrosFiltro)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 75 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
 
    

#line default
#line hidden

#line 85 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <a");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-danger btn-md\"");

WriteAttributeTo(__razor_helper_writer, "onclick", Tuple.Create(" onclick=\"", 4476), Tuple.Create("\"", 4625)
, Tuple.Create(Tuple.Create("", 4486), Tuple.Create("mostrarModalBusqueda(\'modal-", 4486), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4514), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 4514), false)
, Tuple.Create(Tuple.Create("", 4517), Tuple.Create("\',", 4517), true)
, Tuple.Create(Tuple.Create(" ", 4519), Tuple.Create("\'search-table-", 4520), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
              , Tuple.Create(Tuple.Create("", 4534), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 4534), false)
, Tuple.Create(Tuple.Create("", 4537), Tuple.Create("\',", 4537), true)
, Tuple.Create(Tuple.Create(" ", 4539), Tuple.Create("\'", 4540), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                     , Tuple.Create(Tuple.Create("", 4541), Tuple.Create<System.Object, System.Int32>(action

#line default
#line hidden
, 4541), false)
, Tuple.Create(Tuple.Create("", 4548), Tuple.Create("\',", 4548), true)
, Tuple.Create(Tuple.Create(" ", 4550), Tuple.Create("\'", 4551), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                , Tuple.Create(Tuple.Create("", 4552), Tuple.Create<System.Object, System.Int32>(nameProp

#line default
#line hidden
, 4552), false)
, Tuple.Create(Tuple.Create("", 4561), Tuple.Create("\',", 4561), true)
, Tuple.Create(Tuple.Create(" ", 4563), Tuple.Create("\'input-search-", 4564), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                          , Tuple.Create(Tuple.Create("", 4578), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 4578), false)
, Tuple.Create(Tuple.Create("", 4581), Tuple.Create("\',", 4581), true)
, Tuple.Create(Tuple.Create(" ", 4583), Tuple.Create("\'", 4584), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                                 , Tuple.Create(Tuple.Create("", 4585), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 4585), false)
, Tuple.Create(Tuple.Create("", 4588), Tuple.Create("\',", 4588), true)
, Tuple.Create(Tuple.Create(" ", 4590), Tuple.Create("\'", 4591), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                                        , Tuple.Create(Tuple.Create("", 4592), Tuple.Create<System.Object, System.Int32>(hiddenText

#line default
#line hidden
, 4592), false)
, Tuple.Create(Tuple.Create("", 4603), Tuple.Create("\',", 4603), true)
, Tuple.Create(Tuple.Create(" ", 4605), Tuple.Create("\'", 4606), true)

#line 86 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                                                       , Tuple.Create(Tuple.Create("", 4607), Tuple.Create<System.Object, System.Int32>(descriptionText

#line default
#line hidden
, 4607), false)
, Tuple.Create(Tuple.Create("", 4623), Tuple.Create("\')", 4623), true)
);

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-search\"");

WriteLiteralTo(__razor_helper_writer, "></i></a>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 4669), Tuple.Create("\"", 4683)
, Tuple.Create(Tuple.Create("", 4674), Tuple.Create("modal-", 4674), true)

#line 87 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4680), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 4680), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"modal fade\"");

WriteLiteralTo(__razor_helper_writer, " role=\"dialog\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-dialog\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\r\n            <!-- Modal content-->\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-content\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"close\"");

WriteLiteralTo(__razor_helper_writer, " data-dismiss=\"modal\"");

WriteLiteralTo(__razor_helper_writer, ">&times;</button>\r\n                    <h4");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-title\"");

WriteLiteralTo(__razor_helper_writer, ">Búsqueda</h4>\r\n                </div>\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <input");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control textBuscar\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 5156), Tuple.Create("\"", 5177)
, Tuple.Create(Tuple.Create("", 5161), Tuple.Create("input-search-", 5161), true)

#line 97 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5174), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 5174), false)
);

WriteLiteralTo(__razor_helper_writer, " placeholder=\"Escriba para buscar ...\"");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " style=\"margin-top:50px\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <table");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 5312), Tuple.Create("\"", 5333)
, Tuple.Create(Tuple.Create("", 5317), Tuple.Create("search-table-", 5317), true)

#line 99 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5330), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 5330), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"tablaBusqueda table table-bordered table-striped\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                            <thead>\r\n                            <th>EntityID<" +
"/th>\r\n                            ");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 103 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                            

#line default
#line hidden

#line 103 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                             foreach (ControlBusquedaColumna campo in campos)
                            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                                <th>");


#line 105 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
      WriteTo(__razor_helper_writer, campo.Propiedad);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</th>\r\n");


#line 106 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                            <th></th>\r\n                            </thead>\r\n    " +
"                        ");

WriteLiteralTo(__razor_helper_writer, "\r\n                        </table>\r\n                    </div>\r\n                <" +
"/div>\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"modal-footer\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default\"");

WriteLiteralTo(__razor_helper_writer, " data-dismiss=\"modal\"");

WriteLiteralTo(__razor_helper_writer, ">Cerrar</button>\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n " +
"   </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        //agrego las columnas para el buscador actual\r\n        var " +
"columnasActuales = [];\r\n        columnasActuales.push({ \'data\': \'EntityID\', \'vis" +
"ible\': false });\r\n");


#line 124 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
        

#line default
#line hidden

#line 124 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
         foreach (ControlBusquedaColumna campo in campos)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "columnasActuales.push({ \'data\': \'");


#line 126 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                         WriteTo(__razor_helper_writer, campo.Propiedad);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', \'title\': \'");


#line 126 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                                                      WriteTo(__razor_helper_writer, campo.Titulo);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\' });");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 127 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        //guardo las columnas y su id en el array que se define al principio de l" +
"a pagina\r\n        var obj = [];\r\n        obj.push(\'");


#line 130 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n        obj.push(columnasActuales);\r\n        columns.push(obj);\r\n        //g" +
"uardo el reload del buscador actual con su id\r\n        var reload = [];\r\n       " +
" reload.push(\'");


#line 135 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n        reload.push(false);\r\n        reloades.push(reload);\r\n\r\n        var p" +
"arams = []\r\n        //Cada parametro es nombre/id input\r\n");


#line 141 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
        

#line default
#line hidden

#line 141 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
         foreach (ControlBusquedaParametros param in parametrosFiltro)
        {
            //Agrego cada parametro a un array


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            ");

WriteLiteralTo(__razor_helper_writer, "params.push([\'");


#line 144 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
  WriteTo(__razor_helper_writer, param.Tipo);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', \'");


#line 144 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
                 WriteTo(__razor_helper_writer, param.ID);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\'])");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 145 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        parametrosFiltro.push([\'");


#line 146 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
  WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', params]);\r\n    </script>\r\n");


#line 148 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"


#line default
#line hidden
});

#line 148 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\ControlBusquedaHelpers.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
