#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCustomHelpers.Razor
{
    
    #line 6 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 5 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCustomHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class InputsHelpers : System.Web.WebPages.HelperPage
    {

#line 9 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputDate(System.Web.Mvc.HtmlHelper html, string ID)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 10 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"span5 col-md-5 sandbox-container-datepicker form-control\"");

WriteLiteralTo(__razor_helper_writer, " id=\"\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group date\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 13 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
            

#line default
#line hidden

#line 13 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
             if (html.ViewData[ID] != null)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 470), Tuple.Create("\"", 478)

#line 15 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 475), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 475), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 479), Tuple.Create("\"", 489)

#line 15 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 486), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 486), false)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 490), Tuple.Create("\"", 570)

#line 15 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 498), Tuple.Create<System.Object, System.Int32>(Convert.ToDateTime(html.ViewData[ID].ToString()).ToString("dd/MM/yyyy")

#line default
#line hidden
, 498), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

WriteLiteralTo(__razor_helper_writer, "<span");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-fw fa-calendar\"");

WriteLiteralTo(__razor_helper_writer, "></i></span>\r\n");


#line 16 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
            }
            else
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 731), Tuple.Create("\"", 739)

#line 19 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 736), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 736), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 740), Tuple.Create("\"", 750)

#line 19 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 747), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 747), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

WriteLiteralTo(__razor_helper_writer, "<span");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-th\"");

WriteLiteralTo(__razor_helper_writer, "></i></span>\r\n");


#line 20 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </div>\r\n    </div>\r\n");


#line 23 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"


#line default
#line hidden
});

#line 23 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

#line 26 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputDateTime(System.Web.Mvc.HtmlHelper html, string ID)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 27 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"span5 col-md-5 sandbox-container-datetimepicker form-control\"");

WriteLiteralTo(__razor_helper_writer, " id=\"\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group date\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 30 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
            

#line default
#line hidden

#line 30 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
             if (html.ViewData[ID] != null)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <input");

WriteLiteralTo(__razor_helper_writer, " type=\'text\'");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control datetimepicker-control\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 1243), Tuple.Create("\'", 1251)

#line 32 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
   , Tuple.Create(Tuple.Create("", 1248), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 1248), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 1252), Tuple.Create("\"", 1262)

#line 32 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
              , Tuple.Create(Tuple.Create("", 1259), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 1259), false)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 1263), Tuple.Create("\"", 1349)

#line 32 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                          , Tuple.Create(Tuple.Create("", 1271), Tuple.Create<System.Object, System.Int32>(Convert.ToDateTime(html.ViewData[ID].ToString()).ToString("dd/MM/yyyy HH:mm")

#line default
#line hidden
, 1271), false)
);

WriteLiteralTo(__razor_helper_writer, " />");

WriteLiteralTo(__razor_helper_writer, "<span");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-fw fa-calendar\"");

WriteLiteralTo(__razor_helper_writer, "></i></span>\r\n");


#line 33 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
            }
            else
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <input");

WriteLiteralTo(__razor_helper_writer, " type=\'text\'");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control datetimepicker-control\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 1556), Tuple.Create("\'", 1564)

#line 36 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
   , Tuple.Create(Tuple.Create("", 1561), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 1561), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 1565), Tuple.Create("\"", 1575)

#line 36 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
              , Tuple.Create(Tuple.Create("", 1572), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 1572), false)
);

WriteLiteralTo(__razor_helper_writer, " />");

WriteLiteralTo(__razor_helper_writer, "<span");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-fw fa-calendar\"");

WriteLiteralTo(__razor_helper_writer, "></i></span>\r\n");


#line 37 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n        </div>\r\n    </div>\r\n");


#line 41 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"


#line default
#line hidden
});

#line 41 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

#line 44 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputDateRange(System.Web.Mvc.HtmlHelper html, string ID, string IDFechaDesde, string IDFechaHasta, int maxDaysRange, bool tieneTiempo)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 45 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        var nuevoControlDateRangepicker = {id : \'");


#line 47 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                   WriteTo(__razor_helper_writer, ID);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', maxDaysRange :  ");


#line 47 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                         WriteTo(__razor_helper_writer, maxDaysRange);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ", tieneTiempo : ");


#line 47 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                                      WriteTo(__razor_helper_writer, tieneTiempo.ToString().ToLower());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "};\r\n        controlesDateRangePicker.push(nuevoControlDateRangepicker);\r\n    </sc" +
"ript>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"form-group\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        ");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 52 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        

#line default
#line hidden

#line 52 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
         if (html.ViewData[IDFechaDesde] != null)
        {
            //Asigno Valor
            

#line default
#line hidden

#line 55 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
WriteTo(__razor_helper_writer, html.Hidden(IDFechaDesde, Convert.ToDateTime(html.ViewData[IDFechaDesde].ToString()).ToString("dd/MM/yyyy"), new { @class = "rangeFechaDesde" }));


#line default
#line hidden

#line 55 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                                                                                                                             
        }
        else
        {
            

#line default
#line hidden

#line 59 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
WriteTo(__razor_helper_writer, html.Hidden(IDFechaDesde, null, new { @class = "rangeFechaDesde" }));


#line default
#line hidden

#line 59 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                                                
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 62 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        

#line default
#line hidden

#line 62 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
         if (html.ViewData[IDFechaHasta] != null)
        {
            //Asigno Valor
            

#line default
#line hidden

#line 65 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
WriteTo(__razor_helper_writer, html.Hidden(IDFechaHasta, Convert.ToDateTime(html.ViewData[IDFechaHasta].ToString()).ToString("dd/MM/yyyy"), new { @class = "rangeFechaHasta" }));


#line default
#line hidden

#line 65 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                                                                                                                             
        }
        else
        {
            

#line default
#line hidden

#line 69 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
WriteTo(__razor_helper_writer, html.Hidden(IDFechaHasta, null, new { @class = "rangeFechaHasta" }));


#line default
#line hidden

#line 69 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                                                
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group daterangepicker-wrapper\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control pull-right daterangepicker-control\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 3165), Tuple.Create("\"", 3173)

#line 72 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
           , Tuple.Create(Tuple.Create("", 3170), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 3170), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 3174), Tuple.Create("\"", 3184)

#line 72 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                      , Tuple.Create(Tuple.Create("", 3181), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 3181), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-calendar fa-fw\"");

WriteLiteralTo(__razor_helper_writer, "></i>\r\n            </div>\r\n        </div><!-- /.input group -->\r\n    </div>");

WriteLiteralTo(__razor_helper_writer, "<!-- /.form group -->\r\n");


#line 78 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"


#line default
#line hidden
});

#line 78 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

#line 81 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputMaskNumeric(System.Web.Mvc.HtmlHelper html, string ID, int enteros, int decimales)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 82 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        var nuevoControlInputMaskNumerico = {id : \'");


#line 84 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                     WriteTo(__razor_helper_writer, ID);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', enteros :  ");


#line 84 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                      WriteTo(__razor_helper_writer, enteros);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ", decimales : ");


#line 84 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                            WriteTo(__razor_helper_writer, decimales);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "};\r\n        inputsMaskNumericos.push(nuevoControlInputMaskNumerico);\r\n    </scrip" +
"t>\r\n");


#line 87 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
if (html.ViewData[ID] != null)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 3778), Tuple.Create("\"", 3786)

#line 89 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 3783), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 3783), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 3787), Tuple.Create("\"", 3797)

#line 89 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 3794), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 3794), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"input-mask-numeric-control form-control\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 90 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
else
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 3877), Tuple.Create("\"", 3885)

#line 93 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 3882), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 3882), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 3886), Tuple.Create("\"", 3896)

#line 93 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 3893), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 3893), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"input-mask-numeric-control form-control\"");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 3945), Tuple.Create("\"", 3971)

#line 93 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
          , Tuple.Create(Tuple.Create("", 3953), Tuple.Create<System.Object, System.Int32>(html.ViewData[ID]

#line default
#line hidden
, 3953), false)
);

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 94 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}



#line default
#line hidden
});

#line 96 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

#line 99 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputMaskNumeric(System.Web.Mvc.HtmlHelper html, string ID, int enteros, int decimales, string extraClasses, string valor, string opcionesAdicionales)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 100 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        var nuevoControlInputMaskNumerico = {id : \'");


#line 102 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                     WriteTo(__razor_helper_writer, ID);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', enteros :  ");


#line 102 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                      WriteTo(__razor_helper_writer, enteros);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ", decimales : ");


#line 102 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                            WriteTo(__razor_helper_writer, decimales);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "};\r\n        inputsMaskNumericos.push(nuevoControlInputMaskNumerico);\r\n    </scrip" +
"t>\r\n");


#line 105 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
extraClasses += " input-mask-numeric-control form-control";
if (string.Empty.Equals(valor))
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 4507), Tuple.Create("\"", 4515)

#line 108 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4512), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 4512), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 4516), Tuple.Create("\"", 4526)

#line 108 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4523), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 4523), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 4527), Tuple.Create("\"", 4548)

#line 108 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4535), Tuple.Create<System.Object, System.Int32>(extraClasses

#line default
#line hidden
, 4535), false)
);

WriteLiteralTo(__razor_helper_writer, " ");


#line 108 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                           WriteTo(__razor_helper_writer, opcionesAdicionales);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 109 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
else
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 4601), Tuple.Create("\"", 4609)

#line 112 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4606), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 4606), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 4610), Tuple.Create("\"", 4620)

#line 112 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4617), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 4617), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 4621), Tuple.Create("\"", 4642)

#line 112 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4629), Tuple.Create<System.Object, System.Int32>(extraClasses

#line default
#line hidden
, 4629), false)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 4643), Tuple.Create("\"", 4657)

#line 112 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 4651), Tuple.Create<System.Object, System.Int32>(valor

#line default
#line hidden
, 4651), false)
);

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 113 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}



#line default
#line hidden
});

#line 115 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

#line 118 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputMaskNumericMoney(System.Web.Mvc.HtmlHelper html, string ID, int enteros, int decimales)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 119 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        var nuevoControlInputMaskNumerico = {id : \'");


#line 121 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                     WriteTo(__razor_helper_writer, ID);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', enteros :  ");


#line 121 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                      WriteTo(__razor_helper_writer, enteros);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ", decimales : ");


#line 121 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
                                                            WriteTo(__razor_helper_writer, decimales);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "};\r\n        inputsMaskNumericos.push(nuevoControlInputMaskNumerico);\r\n    </scrip" +
"t>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 125 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        

#line default
#line hidden

#line 125 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
         if (html.ViewData[ID] != null)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 5125), Tuple.Create("\"", 5133)

#line 127 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5130), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5130), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 5134), Tuple.Create("\"", 5144)

#line 127 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5141), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5141), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"input-mask-numeric-control form-control\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 128 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        }
        else
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 5252), Tuple.Create("\"", 5260)

#line 131 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5257), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5257), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 5261), Tuple.Create("\"", 5271)

#line 131 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5268), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5268), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"input-mask-numeric-control form-control\"");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 5320), Tuple.Create("\"", 5346)

#line 131 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
              , Tuple.Create(Tuple.Create("", 5328), Tuple.Create<System.Object, System.Int32>(html.ViewData[ID]

#line default
#line hidden
, 5328), false)
);

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 132 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-fw fa-dollar\"");

WriteLiteralTo(__razor_helper_writer, "></i></div>\r\n    </div>\r\n");


#line 136 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"


#line default
#line hidden
});

#line 136 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

#line 139 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputPassword(System.Web.Mvc.HtmlHelper html, string ID)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 140 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        if (html.ViewData[ID] != null)\r\n        {\r\n        <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 5675), Tuple.Create("\"", 5683)

#line 144 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5680), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5680), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 5684), Tuple.Create("\"", 5694)

#line 144 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5691), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5691), false)
);

WriteLiteralTo(__razor_helper_writer, " type=\"password\"");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n        }\r\n        else\r\n        {\r\n        <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 5787), Tuple.Create("\"", 5795)

#line 148 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5792), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5792), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 5796), Tuple.Create("\"", 5806)

#line 148 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5803), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 5803), false)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 5807), Tuple.Create("\"", 5833)

#line 148 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 5815), Tuple.Create<System.Object, System.Int32>(html.ViewData[ID]

#line default
#line hidden
, 5815), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"form-control\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n        }\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"fa fa-fw fa-lock\"");

WriteLiteralTo(__razor_helper_writer, "></i></div>\r\n    </div>\r\n");


#line 152 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"


#line default
#line hidden
});

#line 152 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

#line 155 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
public static System.Web.WebPages.HelperResult InputText(System.Web.Mvc.HtmlHelper html, string ID, string iconClass)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 156 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 158 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        

#line default
#line hidden

#line 158 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
         if (html.ViewData[ID] != null)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 6198), Tuple.Create("\"", 6206)

#line 160 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 6203), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 6203), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 6207), Tuple.Create("\"", 6217)

#line 160 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 6214), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 6214), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"form-control\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 161 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        }
        else
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <input");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 6298), Tuple.Create("\"", 6306)

#line 164 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 6303), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 6303), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 6307), Tuple.Create("\"", 6317)

#line 164 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 6314), Tuple.Create<System.Object, System.Int32>(ID

#line default
#line hidden
, 6314), false)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 6318), Tuple.Create("\"", 6344)

#line 164 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 6326), Tuple.Create<System.Object, System.Int32>(html.ViewData[ID]

#line default
#line hidden
, 6326), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"form-control\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n");


#line 165 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 6423), Tuple.Create("\"", 6441)

#line 166 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
, Tuple.Create(Tuple.Create("", 6431), Tuple.Create<System.Object, System.Int32>(iconClass

#line default
#line hidden
, 6431), false)
);

WriteLiteralTo(__razor_helper_writer, "></i></div>\r\n    </div>\r\n");


#line 168 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"


#line default
#line hidden
});

#line 168 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\InputsHelpers.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
