#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCustomHelpers.Razor
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCustomHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class TreeViewHelper : System.Web.WebPages.HelperPage
    {

#line 6 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\TreeViewHelper.cshtml"
public static System.Web.WebPages.HelperResult TreeView()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 7 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\TreeViewHelper.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group search-error\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        Buscar: <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteLiteralTo(__razor_helper_writer, " class=\"search form-control error\"");

WriteLiteralTo(__razor_helper_writer, " id=\"inputError\"");

WriteLiteralTo(__razor_helper_writer, " title=\"Buscar\"");

WriteLiteralTo(__razor_helper_writer, " data-toggle=\"tooltip\"");

WriteLiteralTo(__razor_helper_writer, " data-placement=\"bottom\"");

WriteLiteralTo(__razor_helper_writer, " />\r\n    </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"aciTree aciTreeBig aciTreeArrow aciTreeNoBranches\"");

WriteLiteralTo(__razor_helper_writer, " id=\"tree\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\r\n    </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <button");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-danger btn-xs\"");

WriteLiteralTo(__razor_helper_writer, " onclick=\"CleanTreeSelection(); return false;\"");

WriteLiteralTo(__razor_helper_writer, ">Limpiar</button>\r\n");


#line 15 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\TreeViewHelper.cshtml"


#line default
#line hidden
});

#line 15 "C:\ProyectoMVCBase\ProyectoBase\MvcCustomHelpers\Views\Helpers\TreeViewHelper.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
